### ISSUE TITLE
User Registration and Login Page

### ISSUE THREAD

**Issue by ParamToor** [ParamToor/SafeWalk#1]
## Todo

- [ ] create wireframe for main screens
- [ ] design login and registration pages (front-end)
- [ ] user registration and authorization
